# Generated by Django 4.2.2 on 2023-12-06 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pricings",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Services",
        ),
        migrations.DeleteModel(
            name="Reviews",
        ),
    ]
