# Generated by Django 4.2.2 on 2023-12-06 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0002_delete_pricings_remove_reviews_customer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blogs",
            new_name="blog",
        ),
    ]
