# Generated by Django 4.2.2 on 2023-12-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tech", "0003_rename_blogs_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
